---
title: "PY795 Presentation"
subtitle: "Yes, I did this on RStudio; <br/> Yes, I am sorry"
author: 
institute: 
date: "Today: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---
# Our team members are:

- Alejandro Anguera
- Emily Jensen
- Emily Oliver
- Phoebe Penfold
- Brontë Rapps

---
# Alejandro Anguera:

- Research interests: *Evolutionary and Forensic Psychology*
- Interesting fact: *PhD in the trash*
- Boring fact: *Toes*

---
# Emily Jensen:
- Research interests: *Sleep*
- Interesting fact: *Snow on birthday*
- Boring fact: *1/8th Danish*

---
# Emily Oliver:
- Research interests: *Social LGBTQ+*
- Interesting fact: *Ross Kemp*
- Boring fact: *Ham Sandwiches*

---
# Phoebe Penfold:
- Research interests: *Eating Disorders*
- Interesting fact: *Qualified dental nurse*
- Boring fact: *Has revolved 26 times around the sun*

---
# Brontë Rapps:
- Research interests: *Victimisation experiences, LGBTQ+*
- Interesting fact: *Has a great love for plants*
- Boring fact: *Granola bar*

---
# The End

I couldn't get a gif to work :(

So here you go:

*That's all folks*
